# ============================================================================
# FINANCEPY EXAMPLES - BondZero
# ============================================================================
#
# Copyright (C) 2018-2026 Dominic O'Kane
#
# This example demonstrates several calculations for zero-coupon bonds:
#
#   1. Yield to maturity and accrued interest
#   2. Holding-period return, IRR and P&L
#   3. The relationship between bond price and yield
#
# A zero-coupon bond makes no periodic coupon payments. Its return is
# generated by the difference between its purchase price and the amount
# received at maturity.
# ============================================================================

import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from financepy.products.bonds.bond import YTMCalcType
from financepy.products.bonds.bond_zero import BondZero
from financepy.utils.date import Date
from financepy.utils.format_graphs import set_plot_style

set_plot_style()

# ============================================================================
# 1. BOND ZERO
# ============================================================================
#
# Construct a short-dated zero-coupon bond and calculate:
#
#   - yield to maturity from an observed clean price
#   - accrued interest for a face amount of 100
#
# For a zero-coupon bond, accrued interest reflects the accretion of the
# issue discount rather than accrued coupon payments.
# ============================================================================

print("\n" + "=" * 100)
print("1. BOND ZERO")
print("=" * 100)

issue_dt = Date(25, 7, 2022)
maturity_dt = Date(24, 10, 2022)

face_amount = 100.0
issue_price = 99.6410

bond = BondZero(
    issue_dt,
    maturity_dt,
    issue_price,
)

settle_dt = Date(8, 8, 2022)
clean_price = 99.6504

ytm = bond.yield_to_maturity(
    settle_dt,
    clean_price,
)

accrued_interest = bond.accrued_interest(
    settle_dt,
    face_amount,
)

print("\n" + "-" * 58)
print(f"{'FIELD':<30}{'VALUE':>20}")
print("-" * 58)

print(f"{'Issue Date':<30}" f"{str(issue_dt):>20}")

print(f"{'Maturity Date':<30}" f"{str(maturity_dt):>20}")

print(f"{'Settlement Date':<30}" f"{str(settle_dt):>20}")

print(f"{'Issue Price':<30}" f"{issue_price:20.6f}")

print(f"{'Clean Price':<30}" f"{clean_price:20.6f}")

print(f"{'Yield to Maturity (%)':<30}" f"{ytm * 100.0:20.6f}")

print(f"{'Accrued Interest':<30}" f"{accrued_interest:20.6f}")

print("-" * 58)


# ============================================================================
# 2. BOND ZERO RATE OF RETURN
# ============================================================================
#
# This section uses a set of purchase and sale scenarios stored in the
# accompanying CSV file.
#
# For each scenario:
#
#   - the purchase price is calculated from the purchase yield
#   - the sale price is calculated from the sale yield
#   - the holding-period return is calculated
#   - the internal rate of return is calculated
#   - the resulting P&L is reported
#
# This illustrates how changes in yield affect the realised return from
# holding a zero-coupon bond between two dates.
# ============================================================================

print("\n" + "=" * 100)
print("2. BOND ZERO RATE OF RETURN")
print("=" * 100)


# ============================================================================
# 2.1 LOAD RETURN SCENARIOS
# ============================================================================

here = os.path.dirname(os.path.abspath(__file__))

data_path = os.path.join(
    here,
    "data",
    "test_cases_bond_zero_ror.csv",
)

df = pd.read_csv(
    data_path,
    parse_dates=[
        "buy_date",
        "sell_date",
    ],
)


# ============================================================================
# 2.2 CONSTRUCT ZERO-COUPON BOND
# ============================================================================

bond = BondZero(
    issue_dt=Date(23, 7, 2021),
    maturity_dt=Date(24, 8, 2022),
    issue_price=97.67,
)


# ============================================================================
# 2.3 CALCULATE HOLDING-PERIOD RETURNS
# ============================================================================

print(
    "\n"
    f"{'BOND CODE':<14}"
    f"{'BUY DATE':<14}"
    f"{'BUY YTM (%)':>14}"
    f"{'BUY PRICE':>14}"
    f"{'SELL DATE':>14}"
    f"{'SELL YTM (%)':>15}"
    f"{'SELL PRICE':>14}"
    f"{'RETURN (%)':>14}"
    f"{'IRR (%)':>14}"
    f"{'P&L':>14}"
)

print("-" * 135)

for row in df.itertuples(index=False):

    buy_dt = Date(
        row.buy_date.day,
        row.buy_date.month,
        row.buy_date.year,
    )

    sell_dt = Date(
        row.sell_date.day,
        row.sell_date.month,
        row.sell_date.year,
    )

    # Calculate the dirty purchase price from the purchase yield.

    buy_price = bond.dirty_price_from_ytm(
        buy_dt,
        row.buy_ytm,
        YTMCalcType.ZERO,
    )

    # Calculate the dirty sale price from the sale yield.

    sell_price = bond.dirty_price_from_ytm(
        sell_dt,
        row.sell_ytm,
        YTMCalcType.ZERO,
    )

    # Calculate the simple holding-period return, annualised IRR and P&L.

    simple_return, irr, pnl = bond.calc_ror(
        buy_dt,
        sell_dt,
        row.buy_ytm,
        row.sell_ytm,
    )

    print(
        f"{str(row.bond_code):<14}"
        f"{str(buy_dt):<14}"
        f"{row.buy_ytm * 100.0:14.6f}"
        f"{buy_price:14.6f}"
        f"{str(sell_dt):>14}"
        f"{row.sell_ytm * 100.0:15.6f}"
        f"{sell_price:14.6f}"
        f"{simple_return * 100.0:14.6f}"
        f"{irr * 100.0:14.6f}"
        f"{pnl:14.6f}"
    )

print("-" * 135)


# ============================================================================
# 3. ZERO-COUPON BOND PRICE VERSUS YIELD
# ============================================================================
#
# A zero-coupon bond has a single cash flow at maturity. This makes it a
# particularly clear example of the inverse relationship between bond price
# and yield.
#
# The bond is repriced over a range of yields from 0.10% to 8.00%.
# ============================================================================

print("\n" + "=" * 100)
print("3. ZERO-COUPON BOND PRICE VERSUS YIELD")
print("=" * 100)

plot_bond = BondZero(
    Date(25, 7, 2022),
    Date(24, 10, 2022),
    99.6410,
)

plot_settle_dt = Date(
    8,
    8,
    2022,
)

plot_yields = np.linspace(
    0.001,
    0.08,
    80,
)

plot_prices = [
    plot_bond.dirty_price_from_ytm(
        plot_settle_dt,
        yld,
        YTMCalcType.ZERO,
    )
    for yld in plot_yields
]


# ============================================================================
# 3.1 SELECTED PRICE / YIELD VALUES
# ============================================================================
#
# Print a small selection of points from the curve so that the numerical
# relationship can also be inspected without relying only on the plot.
# ============================================================================

print("\n" f"{'YIELD (%)':>16}" f"{'DIRTY PRICE':>20}")

print("-" * 36)

for i in range(
    0,
    len(plot_yields),
    10,
):
    print(f"{plot_yields[i] * 100.0:16.6f}" f"{plot_prices[i]:20.6f}")

print("-" * 36)


# ============================================================================
# 3.2 PLOT PRICE / YIELD RELATIONSHIP
# ============================================================================

plt.figure()

plt.plot(
    plot_yields * 100.0,
    plot_prices,
)

plt.xlabel("Yield to Maturity (%)")
plt.ylabel("Dirty Price per 100 Face")
plt.title("Zero-Coupon Bond Price versus Yield")
plt.grid(True)
plt.show()
