name: unit test action

on: [push, pull_request]

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v7

      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install --no-deps .[test]

      - name: show package is importable
        run: |
          python -c "import financepy as fp; print(fp.__version__)"

      - name: show environment
        run: |
          pip --version
          python -c "import financepy as fp; print(fp.__version__)"
          python -c "import numpy, scipy, numba, llvmlite; print(numpy.__version__, scipy.__version__, numba.__version__, llvmlite.__version__)"
          pip freeze

      - name: unit tests
        run: |
          pytest -vv
